### ISSUE TITLE
Request: Mojave Installer Kexts

### ISSUE THREAD

**Issue by dxf** [IOIIIO/AMDVanilla#1]
As per title.

**Comment by im-not-a-dev** [comment]
Mojave will have a seperate guide released for it in the near future.
Contact @dhinakg if you are interested in testing.

**Comment by im-not-a-dev** [comment]
Guide released now as [AMDVanilla](https://github.com/hackintosh-guides/AMDVanilla) over at @hackintosh-guides. Available for viewing at https://amd-osx.com/kb/guides/MJ/.
